package com.aviv.capturehelper.model.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "ALBUM_DATA".
 */
public class AlbumData implements Serializable {

    private Long id;
    private String name;
    private String path;
    private java.util.Date date;
    private Boolean isnew;
    private Boolean isfavorite;
    private String jsonobject;

    public AlbumData() {
    }

    public AlbumData(Long id) {
        this.id = id;
    }

    public AlbumData(Long id, String name, String path, java.util.Date date, Boolean isnew, Boolean isfavorite, String jsonobject) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.date = date;
        this.isnew = isnew;
        this.isfavorite = isfavorite;
        this.jsonobject = jsonobject;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Boolean getIsnew() {
        return isnew;
    }

    public void setIsnew(Boolean isnew) {
        this.isnew = isnew;
    }

    public Boolean getIsfavorite() {
        return isfavorite;
    }

    public void setIsfavorite(Boolean isfavorite) {
        this.isfavorite = isfavorite;
    }

    public String getJsonobject() {
        return jsonobject;
    }

    public void setJsonobject(String jsonobject) {
        this.jsonobject = jsonobject;
    }

}
