package com.aviv.capturehelper.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.aviv.capturehelper.model.dao.ImageData;
import com.aviv.capturehelper.model.dao.AlbumData;

import com.aviv.capturehelper.model.dao.ImageDataDao;
import com.aviv.capturehelper.model.dao.AlbumDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageDataDaoConfig;
    private final DaoConfig albumDataDaoConfig;

    private final ImageDataDao imageDataDao;
    private final AlbumDataDao albumDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageDataDaoConfig = daoConfigMap.get(ImageDataDao.class).clone();
        imageDataDaoConfig.initIdentityScope(type);

        albumDataDaoConfig = daoConfigMap.get(AlbumDataDao.class).clone();
        albumDataDaoConfig.initIdentityScope(type);

        imageDataDao = new ImageDataDao(imageDataDaoConfig, this);
        albumDataDao = new AlbumDataDao(albumDataDaoConfig, this);

        registerDao(ImageData.class, imageDataDao);
        registerDao(AlbumData.class, albumDataDao);
    }
    
    public void clear() {
        imageDataDaoConfig.getIdentityScope().clear();
        albumDataDaoConfig.getIdentityScope().clear();
    }

    public ImageDataDao getImageDataDao() {
        return imageDataDao;
    }

    public AlbumDataDao getAlbumDataDao() {
        return albumDataDao;
    }

}
