package com.aviv.capturehelper.model.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMAGE_DATA".
 */
public class ImageData {

    private Long id;
    private String name;
    private String path;
    private Integer AlbumIdx;
    private java.util.Date date;
    private String jsonobject;

    public ImageData() {
    }

    public ImageData(Long id) {
        this.id = id;
    }

    public ImageData(Long id, String name, String path, Integer AlbumIdx, java.util.Date date, String jsonobject) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.AlbumIdx = AlbumIdx;
        this.date = date;
        this.jsonobject = jsonobject;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Integer getAlbumIdx() {
        return AlbumIdx;
    }

    public void setAlbumIdx(Integer AlbumIdx) {
        this.AlbumIdx = AlbumIdx;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getJsonobject() {
        return jsonobject;
    }

    public void setJsonobject(String jsonobject) {
        this.jsonobject = jsonobject;
    }

}
